### ISSUE TITLE
Ещё ошибка

### ISSUE THREAD

**Issue by Cujoko** [Cujoko/git-hooks-1c#2]
```
d:\Dev\1С\evotor-1c-8 (prfilter)
(evotor-1c-8) λ git status
On branch prfilter
Your branch is up to date with 'origin/prfilter'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    tests/Выгрузка. Сценарий.epf
        deleted:    tests/Документы. НТТ.epf
        deleted:    tests/Документы. Общие.epf
        deleted:    tests/Документы. Оптовый и розничный.epf
        deleted:    tests/Загрузка. Сценарий.epf
        deleted:    tests/Общие.epf
        deleted:    tests/Сущности. Сценарий.epf

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        cjk-evotor.epf

no changes added to commit (use "git add" and/or "git commit -a")

d:\Dev\1С\evotor-1c-8 (prfilter)
(evotor-1c-8) λ git add .

d:\Dev\1С\evotor-1c-8 (prfilter)
(evotor-1c-8) λ git commit -m "Удалит epf-файлы, в который уже раз ошибочно попавшие в репозиторий"
UnpackToFolder. Input file not found!
[19-05-25 15:45:10,129][git_hooks_1c.pre_commit:108][ERROR] Command '['d:\\Work\\Tools\\1С\\V8Unpack\\V8Unpack.exe', '-P', 'd:\\Dev\\1С\\evotor-1c-8\\tests\\Выгрузка. Сценарий.epf', 'd:\\Dev\\1С\\evotor-1c-8\\tests\\Выгрузка. Сценарий_epf_src']' returned non-zero exit status 4294967295.
Traceback (most recent call last):
  File "d:\dev\python\git-hooks-1c\git_hooks_1c\pre_commit.py", line 93, in run
    for_indexing_source_dir_fullpaths = parse(for_processing_file_fullpaths)
  File "d:\dev\python\git-hooks-1c\git_hooks_1c\pre_commit.py", line 60, in parse
    parser.run(file_fullpath, source_dir_fullpath)
  File "c:\users\cujoko\envs\git-hooks-1c\lib\site-packages\parse_1c_build\parse.py", line 56, in run
    exit_code = subprocess.check_call(args_au, stdout=open(os.devnull, 'w'))
  File "c:\program files (x86)\python37\Lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['d:\\Work\\Tools\\1С\\V8Unpack\\V8Unpack.exe', '-P', 'd:\\Dev\\1С\\evotor-1c-8\\tests\\Выгрузка. Сценарий.epf', 'd:\\Dev\\1С\\evotor-1c-8\\tests\\Выгрузка. Сценарий_epf_src']' returned non-zero exit status 4294967295.
```

**Comment by Cujoko** [comment]
epf-файлов на диске нет, но скрипт пытается их распаковать.

**Comment by Cujoko** [comment]
```
d:\Dev\1С\evotor-1c-8 (prfilter)
(evotor-1c-8) λ git status
On branch prfilter
Your branch is up to date with 'origin/prfilter'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        deleted:    tests/Выгрузка. Сценарий.epf
        deleted:    tests/Документы. НТТ.epf
        deleted:    tests/Документы. Общие.epf
        deleted:    tests/Документы. Оптовый и розничный.epf
        deleted:    tests/Загрузка. Сценарий.epf
        deleted:    tests/Общие.epf
        deleted:    tests/Сущности. Сценарий.epf


d:\Dev\1С\evotor-1c-8 (prfilter)
(evotor-1c-8) λ git commit -m "Удалит epf-файлы"
UnpackToFolder. Input file not found!
[19-05-25 15:55:09,152][git_hooks_1c.pre_commit:108][ERROR] Command '['d:\\Work\\Tools\\1С\\V8Unpack\\V8Unpack.exe', '-P', 'd:\\Dev\\1С\\evotor-1c-8\\tests\\Выгрузка. Сценарий.epf', 'd:\\Dev\\1С\\evotor-1c-8\\tests\\Выгрузка. Сценарий_epf_src']' returned non-zero exit status 4294967295.
Traceback (most recent call last):
  File "d:\dev\python\git-hooks-1c\git_hooks_1c\pre_commit.py", line 93, in run
    for_indexing_source_dir_fullpaths = parse(for_processing_file_fullpaths)
  File "d:\dev\python\git-hooks-1c\git_hooks_1c\pre_commit.py", line 60, in parse
    parser.run(file_fullpath, source_dir_fullpath)
  File "c:\users\cujoko\envs\git-hooks-1c\lib\site-packages\parse_1c_build\parse.py", line 56, in run
    exit_code = subprocess.check_call(args_au, stdout=open(os.devnull, 'w'))
  File "c:\program files (x86)\python37\Lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['d:\\Work\\Tools\\1С\\V8Unpack\\V8Unpack.exe', '-P', 'd:\\Dev\\1С\\evotor-1c-8\\tests\\Выгрузка. Сценарий.epf', 'd:\\Dev\\1С\\evotor-1c-8\\tests\\Выгрузка. Сценарий_epf_src']' returned non-zero exit status 4294967295.

d:\Dev\1С\evotor-1c-8 (prfilter)
(evotor-1c-8) λ git status
On branch prfilter
Your branch is up to date with 'origin/prfilter'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        deleted:    tests/Выгрузка. Сценарий.epf
        deleted:    tests/Документы. НТТ.epf
        deleted:    tests/Документы. Общие.epf
        deleted:    tests/Документы. Оптовый и розничный.epf
        deleted:    tests/Загрузка. Сценарий.epf
        deleted:    tests/Общие.epf
        deleted:    tests/Сущности. Сценарий.epf

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    tests/Выгрузка. Сценарий_epf_src/a947ff75-4794-4c1c-9855-c3c674486b72.0/info
        deleted:    tests/Выгрузка. Сценарий_epf_src/a947ff75-4794-4c1c-9855-c3c674486b72.0/text
        deleted:    tests/Выгрузка. Сценарий_epf_src/b353bbf2-6172-4ccc-834b-639ea144bef3
        deleted:    tests/Выгрузка. Сценарий_epf_src/copyinfo
        deleted:    tests/Выгрузка. Сценарий_epf_src/root
        deleted:    tests/Выгрузка. Сценарий_epf_src/version
        deleted:    tests/Выгрузка. Сценарий_epf_src/versions
```
